heat_template_version: 2014-10-16

description: >
 example node 
parameters:
  init_script:
    type: string
    description: init script
  mgm_net:
    type: string
    description: id of the management net
  key_name:
    type: string
    description: Name of keypair to assign to servers
  image:
    type: string
    default: Ubuntu 14.04 sys11-cloudimg amd64
    description: Name of image to use for servers
  flavor:
    type: string
    default: m1.tiny
    description: Flavor to use for nodes
  public_net_id:
    type: string
    default: dc4d2dfb-f8d2-461c-9f16-636edbf99a0f
    description: ID of public network for which floating IP addresses will be allocated

resources:
  ### Example node ###
  ##########################
  exampleserver:
    type: OS::Nova::Server
    properties:
      name: exampleserver01
      image: { get_param: image }
      flavor: { get_param: flavor }
      config_drive: 'true'
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: exampleserver_port }
      metadata:
        puppetmaster: puppetmaster.local
        sys11_topics: "ssh base puppet-agent"
        stack_name: { get_param: 'OS::stack_name' }
      user_data_format: RAW  # Leave this in.
      user_data: { get_param: init_script }

  allow_ssh:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming ssh traffic from anywhere.
      name: ssh incoming
      rules: [{direction: ingress, remote_ip_prefix: 0.0.0.0/0, port_range_min: 22, port_range_max: 22, protocol: tcp} ]

  allow_http:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming ssh traffic from anywhere.
      name: ssh incoming
      rules: [{direction: ingress, remote_ip_prefix: 0.0.0.0/0, port_range_min: 80, port_range_max: 80, protocol: tcp} ]

  exampleserver_port:
    type: OS::Neutron::Port
    properties:
      security_groups: [ {get_resource: allow_http}, {get_resource: allow_ssh} ]
      network_id: { get_param: mgm_net }

  exampleserver_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: exampleserver_port }
